// src/constants/carData.js
export const cars = [
  {
    id:           "930-turbo",
    name:         "911 Turbo 3.3",
    model_code:   "930",
    year:         1977,
    era:          "70s",
    class:        "B",
    tagline:      "The Original Widowmaker",
    description:  "The 930 Turbo terrified a generation. Sudden, savage turbo lag followed by a wall of boost that overwhelmed its rear-engine chassis — it demanded total respect or it took you off the road.",
    price:        "DM 65,880 (1977)",
    image:        "/images/cars/930-turbo.jpg",
    model:        "/models/911-turbo.glb",
    accentColor:  "#C8A96E",
    engineSound:      "911-turbo",
    engineCharacter:  "Laggy turbo spool, then a savage boost surge that overwhelms the rear wheels",
    stats: {
      topSpeed:     { value: 260,  unit: "km/h"   },
      acceleration: { value: 5.4,  unit: "0–100s" },
      horsepower:   { value: 300,  unit: "hp"     },
      torque:       { value: 412,  unit: "Nm"     },
      weight:       { value: 1140, unit: "kg"     },
      engine:       { value: "3.3L Turbocharged Flat-Six" },
      drivetrain:   { value: "RWD"                        },
      transmission: { value: "4-spd Manual"               },
    },
    radarStats: [
      { axis: "Power",        value: 52, rawValue: 300,  rawUnit: "hp"   },
      { axis: "Torque",       value: 51, rawValue: 412,  rawUnit: "Nm"   },
      { axis: "Top Speed",    value: 50, rawValue: 260,  rawUnit: "km/h" },
      { axis: "Acceleration", value: 51, rawValue: 5.4,  rawUnit: "s"    },
      { axis: "Handling",     value: 53, rawValue: null, rawUnit: null   },
      { axis: "Braking",      value: 50, rawValue: null, rawUnit: null   },
      { axis: "Weight",       value: 74, rawValue: 1140, rawUnit: "kg"   },
      { axis: "Pwr/Weight",   value: 53, rawValue: 263,  rawUnit: "hp/t" },
      { axis: "Technology",   value: 50, rawValue: null, rawUnit: null   },
    ],
    dossier: {
      provenance: {
        history: "The 930 was born from a regulatory gamble. Porsche needed a production car to homologate the turbocharged 934 and 935 racers for Group 4 and Group 5 competition. What emerged from Weissach in 1975 was something far more consequential than a race-car proxy — it was the first Porsche to carry the Turbo badge, and it rewrote the rules of what a road car could demand from its driver. The 3.3-litre engine arrived in 1977 with an air-to-air intercooler grafted onto the already-extravagant whale-tail spoiler, pushing output to 300 hp and cementing its reputation as the most dangerous car money could buy.",
        specs: {
          engine:        "3.3L Air-Cooled Turbocharged Flat-Six",
          displacement:  "3,299 cc",
          induction:     "Single KKK Turbocharger, Air-to-Air Intercooler",
          gearbox:       "4-Speed Manual (Getrag G50 derived)",
          chassis:       "Galvanised Steel Unibody, Rear-Engine RWD",
          production:    "1975–1989 (21,589 units)",
          basePrice:     "DM 65,880 (1977)",
          origin:        "Stuttgart-Zuffenhausen, West Germany",
        },
      },
      supremacy: [
        {
          rival:     "Ferrari 512 BB",
          tag:       "Grand Tourer",
          advantage: "The 930 outpaced the 512 BB to 100 km/h by over a second and cost less than half the price. Where Ferrari demanded a ritual, Porsche delivered a weapon you could use daily.",
        },
        {
          rival:     "Lamborghini Countach LP400",
          tag:       "Exotic",
          advantage: "The Countach was theatre. The 930 was consequence. Its turbocharged torque overwhelmed the Countach in real-world acceleration and it was infinitely more tractable on public roads.",
        },
        {
          rival:     "BMW 3.0 CSL",
          tag:       "Touring Car",
          advantage: "Porsche's turbocharging architecture gave the 930 nearly double the specific output of BMW's naturally-aspirated straight-six, establishing forced induction as the future of performance road cars.",
        },
      ],
      dossierRadar: [
        { axis: "Lateral G",       value: 52, rawValue: 0.88, rawUnit: "g"       },
        { axis: "Braking Dist.",   value: 50, rawValue: 38,   rawUnit: "m"       },
        { axis: "Pwr Density",     value: 54, rawValue: 90.9, rawUnit: "hp/L"    },
        { axis: "Drag Coeff.",     value: 58, rawValue: 0.39, rawUnit: "Cd"      },
        { axis: "0–200 km/h",      value: 51, rawValue: 18.2, rawUnit: "s"       },
        { axis: "Consumption",     value: 55, rawValue: 16.8, rawUnit: "L/100km" },
        { axis: "Cornering Spd",   value: 53, rawValue: 108,  rawUnit: "km/h"    },
        { axis: "Thermal Eff.",    value: 50, rawValue: 28,   rawUnit: "%"       },
      ],
      chronicle: [
        { year: 1975, title: "The Turbo Arrives", quote: "The industry had no framework for what it was looking at.", body: "Porsche unveils the 930 Turbo at the Paris Motor Show, introducing turbocharged power to the road-car world. The whale-tail spoiler and 260 hp engine shock an industry accustomed to naturally-aspirated refinement.", image: "/images/dossier/930-turbo/930-1.webp" },
        { year: 1977, title: "The 3.3 Awakens", quote: "Three hundred horsepower. No apologies. No safety net.", body: "The intercooled 3.3-litre engine raises output to 300 hp. The expanded whale-tail now houses the air-to-air intercooler. Road testers coin the phrase 'the widowmaker' after a series of lurid slides on wet tarmac.", image: "/images/dossier/930-turbo/930-2.webp" },
        { year: 1989, title: "An Era Ends", quote: "21,589 units. Every one of them a lesson in consequence.", body: "Production of the 930 generation concludes after 21,589 units. The cabin, with its four-spoke wheel and minimalist instrumentation, becomes one of the most iconic interiors in automotive history.", image: "/images/dossier/930-turbo/930-3.webp" },
      ],
    },
    viewerScale:     3.6,
    cameraPosition:  [0, 1.2, 5.5],
    pivotCorrection: 0,
    colorOptions: [
      { name: "Obsidian Black", hex: "#0A0A0A" },
      { name: "Midnight",       hex: "#1A1A2E" },
      { name: "Dark Slate",     hex: "#2C2C2C" },
      { name: "Gunmetal",       hex: "#2A3439" },
      { name: "Carbon",         hex: "#1C1C1C" },
    ],
  },
  {
    id:           "959",
    name:         "959",
    model_code:   "959",
    year:         1987,
    era:          "80s",
    class:        "S",
    tagline:      "The Future Arrived in 1987",
    description:  "The 959 was a decade ahead of everything on the road. AWD, twin-sequential turbos, ride-height control, hollow-spoke magnesium wheels — it was a supercomputer disguised as a supercar.",
    price:        "DM 420,000 (1987)",
    image:        "/images/cars/959.jpg",
    model:        "/models/959.glb",
    accentColor:  "#D5001C",
    engineSound:      "959",
    engineCharacter:  "Twin-sequential turbos with two distinct boost waves — subtle at low RPM, explosive at high",
    stats: {
      topSpeed:     { value: 317,  unit: "km/h"   },
      acceleration: { value: 3.7,  unit: "0–100s" },
      horsepower:   { value: 450,  unit: "hp"     },
      torque:       { value: 500,  unit: "Nm"     },
      weight:       { value: 1450, unit: "kg"     },
      engine:       { value: "2.85L Twin-Sequential Turbo Flat-Six" },
      drivetrain:   { value: "AWD"                                   },
      transmission: { value: "6-spd Manual"                          },
    },
    radarStats: [
      { axis: "Power",        value: 68, rawValue: 450,  rawUnit: "hp"   },
      { axis: "Torque",       value: 67, rawValue: 500,  rawUnit: "Nm"   },
      { axis: "Top Speed",    value: 78, rawValue: 317,  rawUnit: "km/h" },
      { axis: "Acceleration", value: 72, rawValue: 3.7,  rawUnit: "s"    },
      { axis: "Handling",     value: 76, rawValue: null, rawUnit: null   },
      { axis: "Braking",      value: 65, rawValue: null, rawUnit: null   },
      { axis: "Weight",       value: 57, rawValue: 1450, rawUnit: "kg"   },
      { axis: "Pwr/Weight",   value: 67, rawValue: 310,  rawUnit: "hp/t" },
      { axis: "Technology",   value: 82, rawValue: null, rawUnit: null   },
    ],
    dossier: {
      provenance: {
        history: "The 959 began life as the Gruppe B study shown at Frankfurt in 1983 — a concept so audacious that Porsche engineers spent four years turning it into production reality. It was conceived as a Group B rally weapon and endurance racer simultaneously, demanding solutions to engineering problems that did not yet have solutions. The result was the most technologically sophisticated road car ever built at its time of release: a twin-sequential turbocharged flat-six driving all four wheels through a sophisticated torque-splitting system that could distribute drive between axles in real time, years before any rival even contemplated such architecture.",
        specs: {
          engine:        "2.85L Twin-Sequential Turbocharged Flat-Six",
          displacement:  "2,850 cc",
          induction:     "Twin KKK Turbochargers in Sequential Configuration",
          gearbox:       "6-Speed Manual with PSK AWD Transfer Case",
          chassis:       "Steel/Kevlar/Aramid Composite Body, Full AWD",
          production:    "1986–1988 (337 units)",
          basePrice:     "DM 420,000 (1987)",
          origin:        "Weissach Development Centre, West Germany",
        },
      },
      supremacy: [
        {
          rival:     "Ferrari F40",
          tag:       "Supercar",
          advantage: "The 959 arrived two years before the F40 and matched its top speed with the added security of all-wheel drive and a sophisticated traction management system Ferrari's twin-turbo V8 could only dream of.",
        },
        {
          rival:     "Lamborghini Countach 5000 QV",
          tag:       "Exotic",
          advantage: "The 959's PSK torque-vectoring AWD gave it cornering capability the rear-wheel-drive Countach could never match in wet conditions, while its sequential turbos eliminated the lag that plagued contemporary forced-induction rivals.",
        },
        {
          rival:     "BMW M5 E28",
          tag:       "Performance Saloon",
          advantage: "Against the era's definitive performance saloon, the 959 offered 177 additional horsepower, AWD traction, and a 57 km/h higher top speed — rendering the M5's naturally-aspirated philosophy suddenly antiquated.",
        },
      ],
      dossierRadar: [
        { axis: "Lateral G",      value: 72, rawValue: 1.02, rawUnit: "g"       },
        { axis: "Braking Dist.",  value: 68, rawValue: 33,   rawUnit: "m"       },
        { axis: "Pwr Density",    value: 70, rawValue: 157.9,rawUnit: "hp/L"    },
        { axis: "Drag Coeff.",    value: 74, rawValue: 0.31, rawUnit: "Cd"      },
        { axis: "0–200 km/h",     value: 72, rawValue: 12.8, rawUnit: "s"       },
        { axis: "Consumption",    value: 58, rawValue: 18.2, rawUnit: "L/100km" },
        { axis: "Cornering Spd",  value: 74, rawValue: 138,  rawUnit: "km/h"    },
        { axis: "Thermal Eff.",   value: 62, rawValue: 31,   rawUnit: "%"       },
      ],
      chronicle: [
        { year: 1983, title: "Gruppe B Genesis", quote: "A concept so advanced it needed four years to become real.", body: "Porsche reveals the Gruppe B study at the Frankfurt Motor Show. The concept previews twin-turbo AWD architecture that will define the 959's engineering brief. The automotive world struggles to comprehend what it is looking at.", image: "/images/dossier/959/959-1.webp" },
        { year: 1986, title: "Desert Conquest", quote: "First and second. The desert had no answer.", body: "Three factory 959s enter the Paris–Dakar Rally. Two finish first and second overall, validating the AWD system under conditions of extreme heat, sand, and mechanical attrition that would destroy lesser machines.", image: "/images/dossier/959/959-2.webp" },
        { year: 1987, title: "Anatomy of the Future", quote: "Rival engineers studied the PSK differential in disbelief.", body: "Road & Track publishes a full technical dissection of the 959's drivetrain. Engineers from rival manufacturers study the PSK torque-splitting differential in disbelief. The 959 has made everything else look primitive.", image: "/images/dossier/959/959-3.webp" },
      ],
    },
    viewerScale:    2.8,
    cameraPosition: [0, 1.8, 3.8],
    colorOptions: [
      { name: "Silver Metallic",  hex: "#9B9B9B" },
      { name: "Guards Red",       hex: "#D5001C" },
      { name: "Black",            hex: "#0A0A0A" },
      { name: "Slate Grey",       hex: "#4A4A4A" },
      { name: "Grand Prix White", hex: "#F5F5F5" },
    ],
  },
  {
    id:           "993-gt2",
    name:         "911 GT2",
    model_code:   "993",
    year:         1995,
    era:          "90s",
    class:        "S",
    tagline:      "No Safety Net. No Compromises.",
    description:  "The 993 GT2 stripped out the AWD, cranked the boost, and handed you the most ferocious 911 of its era. No traction control. No mercy. Just 430 horsepower through the rear wheels.",
    price:        "$175,000 (1995)",
    image:        "/images/cars/993-gt2.jpg",
    model:        "/models/911-gt2.glb",
    accentColor:  "#F5D000",
    engineSound:      "911-gt2",
    engineCharacter:  "Raw twin-turbo flat-six with no traction control buffer — every throttle input is a conversation with physics",
    stats: {
      topSpeed:     { value: 295,  unit: "km/h"   },
      acceleration: { value: 3.9,  unit: "0–100s" },
      horsepower:   { value: 430,  unit: "hp"     },
      torque:       { value: 580,  unit: "Nm"     },
      weight:       { value: 1295, unit: "kg"     },
      engine:       { value: "3.6L Twin-Turbo Flat-Six" },
      drivetrain:   { value: "RWD"                      },
      transmission: { value: "6-spd Manual"              },
    },
    radarStats: [
      { axis: "Power",        value: 65, rawValue: 430,  rawUnit: "hp"   },
      { axis: "Torque",       value: 74, rawValue: 580,  rawUnit: "Nm"   },
      { axis: "Top Speed",    value: 68, rawValue: 295,  rawUnit: "km/h" },
      { axis: "Acceleration", value: 70, rawValue: 3.9,  rawUnit: "s"    },
      { axis: "Handling",     value: 70, rawValue: null, rawUnit: null   },
      { axis: "Braking",      value: 66, rawValue: null, rawUnit: null   },
      { axis: "Weight",       value: 68, rawValue: 1295, rawUnit: "kg"   },
      { axis: "Pwr/Weight",   value: 70, rawValue: 332,  rawUnit: "hp/t" },
      { axis: "Technology",   value: 55, rawValue: null, rawUnit: null   },
    ],
    dossier: {
      provenance: {
        history: "The 993 GT2 was Porsche's deliberate act of subtraction. While the Carrera 4S added systems and mass, the GT2 programme removed them — stripping the AWD, deleting the traction control, and rewiring the twin-turbo 3.6-litre flat-six for 430 hp delivered with no electronic intermediary between throttle and tarmac. It was homologated for GT2-class racing but sold to road-going customers who understood what they were accepting. The massive fixed rear wing, flared bodywork, and racing-derived suspension geometry made its intentions explicit before you turned a wheel.",
        specs: {
          engine:        "3.6L Air-Cooled Twin-Turbocharged Flat-Six",
          displacement:  "3,600 cc",
          induction:     "Twin KKK K27 Turbochargers",
          gearbox:       "6-Speed Manual G50/52",
          chassis:       "Steel Unibody, Rear-Engine RWD, No Active Aids",
          production:    "1995–1996 (190 road cars)",
          basePrice:     "$175,000 (1995 US)",
          origin:        "Motorsport Department, Weissach, Germany",
        },
      },
      supremacy: [
        {
          rival:     "Ferrari F355",
          tag:       "Sports Car",
          advantage: "The GT2 produced 80 hp more than the F355 and weighed less, translating to a decisive performance advantage at every point on the speedometer — while the Ferrari relied on electronic intervention the Porsche simply refused to install.",
        },
        {
          rival:     "McLaren F1 (Road)",
          tag:       "Hypercar",
          advantage: "At less than a quarter of the McLaren's price, the GT2 offered comparable lateral grip and superior everyday usability, making it the most cost-efficient route to supercar-grade performance in the mid-1990s.",
        },
        {
          rival:     "Dodge Viper RT/10",
          tag:       "American Muscle",
          advantage: "Where the Viper deployed raw cubic displacement, the GT2's twin-turbo architecture delivered superior mid-range torque delivery and a structural rigidity the aluminium-framed Viper could not match on track.",
        },
      ],
      dossierRadar: [
        { axis: "Lateral G",      value: 70, rawValue: 1.06, rawUnit: "g"       },
        { axis: "Braking Dist.",  value: 66, rawValue: 34,   rawUnit: "m"       },
        { axis: "Pwr Density",    value: 68, rawValue: 119.4,rawUnit: "hp/L"    },
        { axis: "Drag Coeff.",    value: 60, rawValue: 0.37, rawUnit: "Cd"      },
        { axis: "0–200 km/h",     value: 68, rawValue: 13.4, rawUnit: "s"       },
        { axis: "Consumption",    value: 57, rawValue: 17.1, rawUnit: "L/100km" },
        { axis: "Cornering Spd",  value: 70, rawValue: 132,  rawUnit: "km/h"    },
        { axis: "Thermal Eff.",   value: 55, rawValue: 29,   rawUnit: "%"       },
      ],
      chronicle: [
        { year: 1995, title: "Born on the Grid", quote: "No traction control. No mercy. Just physics.", body: "Porsche presents the 993 GT2 at the Geneva Motor Show. Its fixed rear wing, massively flared arches, and twin-turbo credentials immediately establish it as the most extreme road-legal 911 in existence.", image: "/images/dossier/993-gt2/gt2-1.jpg" },
        { year: 1995, title: "The Wide Body", quote: "Every proportion announces its purpose.", body: "Close inspection of the GT2's rear arches reveals the full width of the BBS split-rim wheels beneath — 265mm at the front, 285mm at the rear. This is not a touring car. Every proportion announces its purpose.", image: "/images/dossier/993-gt2/gt2-2.webp" },
        { year: 1996, title: "Circuit Proven", quote: "What wins on Sunday, you can buy on Monday.", body: "GT2-class racing validates the road car's architecture under sustained competition. Teams running the 993 GT2 in BPR Global GT Series and early FIA GT demonstrate its endurance-grade reliability at race pace.", image: "/images/dossier/993-gt2/gt2-3.webp" },
      ],
    },
    viewerScale:    2.8,
    cameraPosition: [0, 1.1, 3.8],
    colorOptions: [
      { name: "Racing Yellow",    hex: "#F5D000" },
      { name: "Grand Prix White", hex: "#F5F5F5" },
      { name: "Black",            hex: "#0A0A0A" },
      { name: "Guards Red",       hex: "#D5001C" },
      { name: "Arctic Silver",    hex: "#C0C0C0" },
    ],
  },
  {
    id:           "911-gt1-97",
    name:         "911 GT1",
    model_code:   "996 GT1",
    year:         1997,
    era:          "90s",
    class:        "S",
    tagline:      "Le Mans Came Home",
    description:  "Built for one purpose: to win Le Mans. Porsche homologated just 25 road-legal GT1s. Mid-engine, twin-turbo, carbon-bodied — it is the rarest and most extreme 911 ever to wear a number plate.",
    price:        "$1,500,000 (1997)",
    image:        "/images/cars/911-gt1-97.jpg",
    model:        "/models/911-gt1.glb",
    accentColor:  "#FFFFFF",
    engineSound:      "911-gt1",
    engineCharacter:  "Le Mans-spec twin-turbo six — built to sustain 330 km/h for 24 hours straight",
    stats: {
      topSpeed:     { value: 330,  unit: "km/h"   },
      acceleration: { value: 3.4,  unit: "0–100s" },
      horsepower:   { value: 544,  unit: "hp"     },
      torque:       { value: 650,  unit: "Nm"     },
      weight:       { value: 1050, unit: "kg"     },
      engine:       { value: "3.2L Twin-Turbo Flat-Six (Mid-Mount)" },
      drivetrain:   { value: "RWD"                                   },
      transmission: { value: "6-spd Sequential"                      },
    },
    radarStats: [
      { axis: "Power",        value: 78, rawValue: 544,  rawUnit: "hp"   },
      { axis: "Torque",       value: 80, rawValue: 650,  rawUnit: "Nm"   },
      { axis: "Top Speed",    value: 88, rawValue: 330,  rawUnit: "km/h" },
      { axis: "Acceleration", value: 77, rawValue: 3.4,  rawUnit: "s"    },
      { axis: "Handling",     value: 88, rawValue: null, rawUnit: null   },
      { axis: "Braking",      value: 84, rawValue: null, rawUnit: null   },
      { axis: "Weight",       value: 92, rawValue: 1050, rawUnit: "kg"   },
      { axis: "Pwr/Weight",   value: 84, rawValue: 518,  rawUnit: "hp/t" },
      { axis: "Technology",   value: 72, rawValue: null, rawUnit: null   },
    ],
    dossier: {
      provenance: {
        history: "The 911 GT1 exists because of a loophole and an obsession. FIA GT regulations required manufacturers to homologate a road car to race in the GT1 class — so Porsche built exactly 25 road-legal examples of its Le Mans prototype. The car shares almost nothing with a conventional 911: the engine is mid-mounted behind the driver, the tub is carbon fibre, and the body generates significant aerodynamic downforce. Each road car was delivered with a racing harness, fire suppression system, and a tool kit. It was never intended to be driven to work. It was intended to win the 24 Hours of Le Mans.",
        specs: {
          engine:        "3.2L Water-Cooled Twin-Turbocharged Flat-Six (Mid-Mount)",
          displacement:  "3,164 cc",
          induction:     "Twin Turbochargers, Sequential Configuration",
          gearbox:       "6-Speed Sequential (Porsche G96/96)",
          chassis:       "Carbon Fibre Monocoque, RWD, Racing Suspension",
          production:    "1997–1998 (25 road cars)",
          basePrice:     "$1,500,000 (1997)",
          origin:        "Weissach Motorsport, Germany",
        },
      },
      supremacy: [
        {
          rival:     "Mercedes CLK GTR",
          tag:       "GT1 Rival",
          advantage: "The GT1 class duel with Mercedes was one of the most technically fierce in racing history. Porsche's mid-engine packaging gave superior polar moment of inertia, contributing to the GT1's 1998 Le Mans victory over the CLK.",
        },
        {
          rival:     "McLaren F1 GTR",
          tag:       "GT Racer",
          advantage: "While the McLaren F1 GTR relied on a naturally-aspirated BMW V12, the GT1's twin-turbo architecture provided significantly greater power density and the ability to tune boost for varying fuel loads across a 24-hour race.",
        },
        {
          rival:     "Ferrari F333 SP",
          tag:       "Prototype",
          advantage: "Competing in different classes but sharing circuits, the GT1 demonstrated superior straight-line speed through Mulsanne than Ferrari's prototype, validating Porsche's turbocharged approach against Ferrari's high-revving V12.",
        },
      ],
      dossierRadar: [
        { axis: "Lateral G",      value: 88, rawValue: 1.38, rawUnit: "g"       },
        { axis: "Braking Dist.",  value: 84, rawValue: 27,   rawUnit: "m"       },
        { axis: "Pwr Density",    value: 84, rawValue: 172.0,rawUnit: "hp/L"    },
        { axis: "Drag Coeff.",    value: 72, rawValue: 0.34, rawUnit: "Cd"      },
        { axis: "0–200 km/h",     value: 84, rawValue: 9.8,  rawUnit: "s"       },
        { axis: "Consumption",    value: 62, rawValue: 22.4, rawUnit: "L/100km" },
        { axis: "Cornering Spd",  value: 88, rawValue: 178,  rawUnit: "km/h"    },
        { axis: "Thermal Eff.",   value: 70, rawValue: 34,   rawUnit: "%"       },
      ],
      chronicle: [
        { year: 1996, title: "The Homologation", quote: "25 cars built. Each one a Le Mans prototype with number plates.", body: "Porsche presents the road-legal 911 GT1 at the Paris Motor Show. Journalists are informed that 25 examples will be built to satisfy FIA homologation requirements. The price of $1.5 million renders the question of demand irrelevant.", image: "/images/dossier/911-gt1-97/gt1-1.webp" },
        { year: 1997, title: "Carbon Architecture", quote: "120 kg. The lightest tub Porsche had ever built for a road car.", body: "Factory photographs reveal the GT1's carbon fibre monocoque under construction at Weissach. The tub weighs 120 kg complete — lighter than any steel equivalent. It is the most advanced chassis Porsche has ever put into a road car.", image: "/images/dossier/911-gt1-97/gt1-2.webp" },
        { year: 1998, title: "La Sarthe Conquered", quote: "The 24 Hours ended. Porsche's record stood alone.", body: "The 911 GT1-98 wins the 24 Hours of Le Mans outright. Porsche becomes the most successful manufacturer in Le Mans history. The 25 road cars, already impossibly rare, become historically irreplaceable.", image: "/images/dossier/911-gt1-97/gt1-3.jpg" },
      ],
    },
    viewerScale:    2.8,
    cameraPosition: [0, 1.1, 3.8],
    colorOptions: [
      { name: "Silver",      hex: "#9B9B9B" },
      { name: "Pearl White", hex: "#F5F5F0" },
      { name: "Black",       hex: "#0A0A0A" },
    ],
  },
  {
    id:           "carrera-gt",
    name:         "Carrera GT",
    model_code:   "980",
    year:         2004,
    era:          "2000s",
    class:        "S",
    tagline:      "The Last of the Pure Ones",
    description:  "A naturally aspirated V10 from a Le Mans prototype, a carbon ceramic clutch the size of a CD, and zero driver aids. The Carrera GT is the most visceral, unfiltered supercar Porsche has ever built.",
    price:        "$440,000 (2004)",
    image:        "/images/cars/carrera-gt.jpg",
    model:        "/models/carrera-gt.glb",
    accentColor:  "#D5001C",
    engineSound:      "carrera-gt",
    engineCharacter:  "5.7L V10 screaming to 8,000 RPM — an operatic, spine-tingling note found nowhere else on earth",
    stats: {
      topSpeed:     { value: 330,  unit: "km/h"   },
      acceleration: { value: 3.5,  unit: "0–100s" },
      horsepower:   { value: 612,  unit: "hp"     },
      torque:       { value: 590,  unit: "Nm"     },
      weight:       { value: 1380, unit: "kg"     },
      engine:       { value: "5.7L Naturally Aspirated V10" },
      drivetrain:   { value: "RWD"                          },
      transmission: { value: "6-spd Manual"                 },
    },
    radarStats: [
      { axis: "Power",        value: 85, rawValue: 612,  rawUnit: "hp"   },
      { axis: "Torque",       value: 76, rawValue: 590,  rawUnit: "Nm"   },
      { axis: "Top Speed",    value: 88, rawValue: 330,  rawUnit: "km/h" },
      { axis: "Acceleration", value: 75, rawValue: 3.5,  rawUnit: "s"    },
      { axis: "Handling",     value: 83, rawValue: null, rawUnit: null   },
      { axis: "Braking",      value: 80, rawValue: null, rawUnit: null   },
      { axis: "Weight",       value: 62, rawValue: 1380, rawUnit: "kg"   },
      { axis: "Pwr/Weight",   value: 82, rawValue: 443,  rawUnit: "hp/t" },
      { axis: "Technology",   value: 65, rawValue: null, rawUnit: null   },
    ],
    dossier: {
      provenance: {
        history: "The Carrera GT traces its lineage to a 1999 Le Mans prototype programme that Porsche cancelled when motorsport direction shifted. The V10 engine sat in a Weissach storage room for three years before engineers proposed using it as the centrepiece of a production hypercar. The resulting 980 was built around a carbon fibre monocoque with a carbon-ceramic clutch — a component so light and so precise that it earned its own mythology. No stability control, no traction control, no launch control. The Carrera GT would do exactly what you commanded, and punish any instruction given in error.",
        specs: {
          engine:        "5.7L Naturally Aspirated 68-Degree V10",
          displacement:  "5,733 cc",
          induction:     "Naturally Aspirated, Individual Throttle Bodies",
          gearbox:       "6-Speed Manual with Carbon-Ceramic Clutch",
          chassis:       "Carbon Fibre Monocoque, RWD, Pushrod Suspension",
          production:    "2004–2006 (1,270 units)",
          basePrice:     "$440,000 (2004 US)",
          origin:        "Leipzig, Germany",
        },
      },
      supremacy: [
        {
          rival:     "Ferrari Enzo",
          tag:       "Hypercar",
          advantage: "The Carrera GT matched the Enzo's performance with a naturally-aspirated engine producing a more operatic sound and a driver engagement the semi-automatic Ferrari transmission could never replicate. It was the last analogue argument against digital performance.",
        },
        {
          rival:     "Lamborghini Murciélago",
          tag:       "Exotic",
          advantage: "Despite the Murciélago's larger displacement and AWD traction advantage, the Carrera GT's superior power-to-weight ratio and carbon pushrod suspension gave it decisive track superiority in controlled testing.",
        },
        {
          rival:     "Mercedes SLR McLaren",
          tag:       "Grand Tourer",
          advantage: "Where the SLR prioritised grand touring comfort and supercharged grunt, the Carrera GT delivered raw driver involvement and a 8,000 RPM naturally-aspirated crescendo that the supercharged Mercedes could never acoustically compete with.",
        },
      ],
      dossierRadar: [
        { axis: "Lateral G",      value: 84, rawValue: 1.26, rawUnit: "g"       },
        { axis: "Braking Dist.",  value: 80, rawValue: 29,   rawUnit: "m"       },
        { axis: "Pwr Density",    value: 82, rawValue: 106.8,rawUnit: "hp/L"    },
        { axis: "Drag Coeff.",    value: 70, rawValue: 0.33, rawUnit: "Cd"      },
        { axis: "0–200 km/h",     value: 80, rawValue: 9.9,  rawUnit: "s"       },
        { axis: "Consumption",    value: 54, rawValue: 21.8, rawUnit: "L/100km" },
        { axis: "Cornering Spd",  value: 82, rawValue: 168,  rawUnit: "km/h"    },
        { axis: "Thermal Eff.",   value: 63, rawValue: 32,   rawUnit: "%"       },
      ],
      chronicle: [
        { year: 1999, title: "The Prototype Origin", quote: "A cancelled race programme. An engine too good to forget.", body: "A V10 engine developed for a cancelled Le Mans prototype is placed into storage at Weissach. Engineers argue for its preservation. Three years later it becomes the centrepiece of a car that will define analogue supercar performance for a generation.", image: "/images/dossier/carrera-gt/carreragt-1.webp" },
        { year: 2003, title: "Geneva Revelation", quote: "Journalists searched for metaphors and settled on 'operatic'.", body: "Porsche unveils the production Carrera GT at the Geneva Motor Show. The silver car on the white plinth draws the largest crowd of any stand. The naturally-aspirated V10 sounds like nothing else — journalists struggle for metaphors and settle on 'operatic'.", image: "/images/dossier/carrera-gt/carreragt-2.webp" },
        { year: 2004, title: "The Heart Exposed", quote: "Ten throttle bodies. Zero compromises. One final form.", body: "Production begins in Leipzig. Factory photography reveals the V10's intake trumpets — ten individual throttle bodies breathing without restriction. This engine will never be turbocharged, never be detuned. It exists in its only form.", image: "/images/dossier/carrera-gt/carreragt-3.webp" },
      ],
    },
    viewerScale:    2.8,
    cameraPosition: [0, 1.1, 3.8],
    colorOptions: [
      { name: "Guards Red",       hex: "#D5001C" },
      { name: "Fayence Yellow",   hex: "#C8A028" },
      { name: "Basalt Black",     hex: "#1A1A1A" },
      { name: "Seal Grey",        hex: "#6B6B6B" },
      { name: "Grand Prix White", hex: "#F5F5F5" },
    ],
  },
  {
    id:           "911-gt3-992",
    name:         "911 GT3",
    model_code:   "992",
    year:         2022,
    era:          "2020s",
    class:        "S",
    tagline:      "Born on the Racetrack",
    description:  "Nine thousand RPM. Naturally aspirated. Swan-neck rear wing. The 992 GT3 is the most connected, most alive 911 road car money can buy — and it will embarrass purpose-built track cars at the Nürburgring.",
    price:        "$161,100 (2022)",
    image:        "/images/cars/911-gt3-992.jpg",
    cardImage:    "/images/cars/911-gt3-card.jpg",
    model:        "/models/911-gt3.glb",
    accentColor:  "#D5001C",
    engineSound:      "911-gt3",
    engineCharacter:  "Naturally aspirated flat-six with a 9,000 RPM ceiling — a pure mechanical howl that builds linearly to a screaming crescendo",
    stats: {
      topSpeed:     { value: 318,  unit: "km/h"   },
      acceleration: { value: 3.4,  unit: "0–100s" },
      horsepower:   { value: 510,  unit: "hp"     },
      torque:       { value: 470,  unit: "Nm"     },
      weight:       { value: 1418, unit: "kg"     },
      engine:       { value: "4.0L Naturally Aspirated Flat-Six" },
      drivetrain:   { value: "RWD"                               },
      transmission: { value: "7-spd PDK / 6-spd Manual"          },
    },
    radarStats: [
      { axis: "Power",        value: 76, rawValue: 510,  rawUnit: "hp"   },
      { axis: "Torque",       value: 65, rawValue: 470,  rawUnit: "Nm"   },
      { axis: "Top Speed",    value: 81, rawValue: 318,  rawUnit: "km/h" },
      { axis: "Acceleration", value: 77, rawValue: 3.4,  rawUnit: "s"    },
      { axis: "Handling",     value: 95, rawValue: null, rawUnit: null   },
      { axis: "Braking",      value: 92, rawValue: null, rawUnit: null   },
      { axis: "Weight",       value: 63, rawValue: 1418, rawUnit: "kg"   },
      { axis: "Pwr/Weight",   value: 75, rawValue: 360,  rawUnit: "hp/t" },
      { axis: "Technology",   value: 88, rawValue: null, rawUnit: null   },
    ],
    dossier: {
      provenance: {
        history: "The 992 GT3 is the culmination of twenty-five years of GT3 development, each generation distilling Porsche's racing programme into a road car that remains legally registerable. The 992 generation brings a swan-neck rear wing mounting system derived directly from the 911 RSR race car, rear-axle steering adapted from the Turbo S, and a 4.0-litre naturally-aspirated flat-six that spins to 9,000 RPM and produces 510 hp without a single forced-induction component. Its 7:25.82 lap of the Nürburgring Nordschleife remains the benchmark for production sports cars.",
        specs: {
          engine:        "4.0L Naturally Aspirated Flat-Six (Motorsport-derived)",
          displacement:  "3,996 cc",
          induction:     "Naturally Aspirated, Variable Valve Timing (VarioCam Plus)",
          gearbox:       "7-Speed PDK or 6-Speed Manual",
          chassis:       "Aluminium/Steel Composite, RWD, PDCC, Rear-Axle Steering",
          production:    "2021–present",
          basePrice:     "$161,100 (2022 US)",
          origin:        "Stuttgart-Zuffenhausen, Germany",
        },
      },
      supremacy: [
        {
          rival:     "Ferrari 296 GTB",
          tag:       "Sports Car",
          advantage: "The GT3's naturally-aspirated 9,000 RPM engine provides driver feedback and acoustic engagement that Ferrari's turbocharged V6 hybrid cannot replicate, while its rear-axle steering delivers cornering precision the 296 GTB approaches only with electronic assistance.",
        },
        {
          rival:     "Lamborghini Huracán STO",
          tag:       "Track-Focused",
          advantage: "Back-to-back track testing at the Nürburgring consistently places the GT3 ahead of the Huracán STO. The Porsche's PDCC sway control and superior tyre management across extended sessions give it an endurance advantage the Lamborghini cannot sustain.",
        },
        {
          rival:     "BMW M4 CSL",
          tag:       "Performance Coupe",
          advantage: "The GT3 laps the Nürburgring eleven seconds faster than the M4 CSL while producing a naturally-aspirated soundtrack the turbocharged BMW cannot approach. No comparison between them is genuinely competitive.",
        },
      ],
      dossierRadar: [
        { axis: "Lateral G",      value: 92, rawValue: 1.42, rawUnit: "g"       },
        { axis: "Braking Dist.",  value: 90, rawValue: 28,   rawUnit: "m"       },
        { axis: "Pwr Density",    value: 86, rawValue: 127.6,rawUnit: "hp/L"    },
        { axis: "Drag Coeff.",    value: 65, rawValue: 0.36, rawUnit: "Cd"      },
        { axis: "0–200 km/h",     value: 84, rawValue: 10.8, rawUnit: "s"       },
        { axis: "Consumption",    value: 68, rawValue: 13.2, rawUnit: "L/100km" },
        { axis: "Cornering Spd",  value: 92, rawValue: 182,  rawUnit: "km/h"    },
        { axis: "Thermal Eff.",   value: 76, rawValue: 38,   rawUnit: "%"       },
      ],
      chronicle: [
        { year: 2021, title: "Swan-Neck Born", quote: "Straight from Le Mans. Via Zuffenhausen.", body: "The 992 GT3 is revealed with a swan-neck rear wing mounting system transferred directly from the 911 RSR Le Mans racer. The aerodynamic advantage is measurable. The visual statement is absolute.", image: "/images/dossier/911-gt3-992/gt3-1.webp" },
        { year: 2021, title: "Nine Thousand", quote: "9,000 RPM. Naturally aspirated. In 2021. Porsche.", body: "Porsche publishes the 4.0-litre flat-six's redline: 9,000 RPM. For a naturally-aspirated road engine in 2021, the figure is extraordinary. The intake system visible above the engine reveals individual throttle bodies — no turbos, no compromise.", image: "/images/dossier/911-gt3-992/gt3-2.webp" },
        { year: 2021, title: "The Green Hell Record", quote: "7:25.82. The Nordschleife had a new master.", body: "Andreas Preuninger pilots the 992 GT3 to a 7:25.82 lap of the Nürburgring Nordschleife. The timing board tells the story — it is the fastest production sports car ever to complete the lap.", image: "/images/dossier/911-gt3-992/gt3-3.webp" },
      ],
    },
    viewerScale:    2.8,
    cameraPosition: [0, 1.1, 3.8],
    colorOptions: [
      { name: "Shark Blue",    hex: "#1C3F6E" },
      { name: "Guards Red",    hex: "#D5001C" },
      { name: "GT Silver",     hex: "#9B9B9B" },
      { name: "Jet Black",     hex: "#0A0A0A" },
      { name: "Racing Yellow", hex: "#F5D000" },
    ],
  },
  {
    id:           "taycan-turbo-s",
    name:         "Taycan Turbo S",
    model_code:   "J1",
    year:         2021,
    era:          "2020s",
    class:        "S",
    tagline:      "Electric. Instant. Relentless.",
    description:  "560 kilowatts. 1,050 Nm. Available the instant you ask for it. The Taycan Turbo S dismantles everything you thought you knew about what an electric car should feel like.",
    price:        "$185,000 (2021)",
    image:        "/images/cars/taycan-turbo-s.jpg",
    model:        "/models/taycan-turbo-s.glb",
    accentColor:  "#C8A96E",
    engineSound:      "taycan-turbo-s",
    engineCharacter:  "Instant 1,050 Nm with a rising electric whine — no lag, no buildup, just immediate and total force",
    stats: {
      topSpeed:     { value: 260,  unit: "km/h"   },
      acceleration: { value: 2.8,  unit: "0–100s" },
      horsepower:   { value: 761,  unit: "hp"     },
      torque:       { value: 1050, unit: "Nm"     },
      weight:       { value: 2295, unit: "kg"     },
      engine:       { value: "Dual Electric Motors (800V Architecture)" },
      drivetrain:   { value: "AWD"                                       },
      transmission: { value: "2-spd PDK (rear axle)"                     },
    },
    radarStats: [
      { axis: "Power",        value: 95, rawValue: 761,  rawUnit: "hp"   },
      { axis: "Torque",       value: 95, rawValue: 1050, rawUnit: "Nm"   },
      { axis: "Top Speed",    value: 50, rawValue: 260,  rawUnit: "km/h" },
      { axis: "Acceleration", value: 95, rawValue: 2.8,  rawUnit: "s"    },
      { axis: "Handling",     value: 82, rawValue: null, rawUnit: null   },
      { axis: "Braking",      value: 90, rawValue: null, rawUnit: null   },
      { axis: "Weight",       value: 50, rawValue: 2295, rawUnit: "kg"   },
      { axis: "Pwr/Weight",   value: 78, rawValue: 332,  rawUnit: "hp/t" },
      { axis: "Technology",   value: 95, rawValue: null, rawUnit: null   },
    ],
    dossier: {
      provenance: {
        history: "The Taycan arrived in 2019 carrying the weight of Porsche's entire electrification future on its 800-volt architecture. The Turbo S variant represents the absolute summit of that programme — dual permanent-magnet synchronous motors delivering a combined 761 hp in overboost, all managed through a two-speed PDK transmission on the rear axle that gives the car gear-change behaviour no other electric vehicle can replicate. The 800V system enables 270 kW DC fast charging and thermal management sophisticated enough to sustain repeated high-performance runs without power degradation.",
        specs: {
          engine:        "Dual Permanent-Magnet Synchronous Motors",
          displacement:  "N/A — 800V Architecture, 93.4 kWh Battery",
          induction:     "Electric — Zero Lag, Zero Emissions",
          gearbox:       "2-Speed PDK (Rear Axle) + Single-Speed (Front Axle)",
          chassis:       "Aluminium Space Frame, AWD, PDCC, Rear-Axle Steering",
          production:    "2020–present",
          basePrice:     "$185,000 (2021 US)",
          origin:        "Zuffenhausen, Germany (assembly) / Weissach (development)",
        },
      },
      supremacy: [
        {
          rival:     "Tesla Model S Plaid",
          tag:       "Electric Performance",
          advantage: "The Taycan Turbo S sustains its performance across repeated acceleration runs without thermal throttling — a fundamental engineering advantage the Plaid's tri-motor architecture cannot match under sustained track use.",
        },
        {
          rival:     "Ferrari SF90 Stradale",
          tag:       "Hybrid Hypercar",
          advantage: "While the SF90 combines combustion and electric power, the Taycan's 800V architecture delivers faster DC charging, superior thermal stability, and a driving experience that requires zero management of combustion-electric transition.",
        },
        {
          rival:     "Lamborghini Urus Performante",
          tag:       "Performance SUV",
          advantage: "Sharing a similar price bracket, the Taycan Turbo S delivers equivalent acceleration in a significantly lower centre of gravity package, with regenerative braking contributing to a total braking performance the Urus cannot approach.",
        },
      ],
      dossierRadar: [
        { axis: "Lateral G",      value: 86, rawValue: 1.28, rawUnit: "g"          },
        { axis: "Braking Dist.",  value: 90, rawValue: 27,   rawUnit: "m"          },
        { axis: "Pwr Density",    value: 95, rawValue: 8.15, rawUnit: "kW/kg"      },
        { axis: "Drag Coeff.",    value: 88, rawValue: 0.22, rawUnit: "Cd"         },
        { axis: "0–200 km/h",     value: 92, rawValue: 9.8,  rawUnit: "s"          },
        { axis: "Consumption",    value: 90, rawValue: 24.8, rawUnit: "kWh/100km"  },
        { axis: "Cornering Spd",  value: 84, rawValue: 172,  rawUnit: "km/h"       },
        { axis: "Thermal Eff.",   value: 95, rawValue: 94,   rawUnit: "%"          },
      ],
      chronicle: [
        { year: 2019, title: "The Electric Declaration", quote: "Not an electric car. A Porsche that runs on electricity.", body: "Porsche presents the Taycan at a simultaneous three-continent reveal. The 800V architecture and the retention of a two-speed gearbox signal that this is not a compliance electric vehicle — it is a sports car that happens to be electric.", image: "/images/dossier/taycan-turbo-s/taycan-1.webp" },
        { year: 2020, title: "The Architecture", quote: "3,425 km in 24 hours. The battery never surrendered.", body: "Porsche publishes full technical documentation on the 800V drivetrain and Nardò high-speed oval record run. The Taycan completes 3,425 km in 24 hours at an average speed of 142 km/h — a performance no battery-thermal management system had previously sustained.", image: "/images/dossier/taycan-turbo-s/taycan-2.webp" },
        { year: 2021, title: "The Interior Redefined", quote: "Neither a car cabin nor a tech product. Something entirely new.", body: "The Taycan's curved instrument cluster and passenger display set a new benchmark for electric vehicle interior design. The Mission E concept's promises are delivered in full — the cabin feels like neither a conventional car nor a technology product, but something entirely new.", image: "/images/dossier/taycan-turbo-s/taycan-3.webp" },
      ],
    },
    viewerScale:    2.8,
    cameraPosition: [0, 1.1, 3.8],
    colorOptions: [
      { name: "Frozen Blue",   hex: "#5B8FA8" },
      { name: "Gentian Blue",  hex: "#1C3F6E" },
      { name: "Carrara White", hex: "#F0EDE8" },
      { name: "Volcano Grey",  hex: "#4A4A4A" },
      { name: "Night Blue",    hex: "#1A1F3C" },
    ],
  },
];

export const eras = ["70s", "80s", "90s", "2000s", "2020s"];
export const classLabels = {
  S: { label: "Class S", description: "Hypercar tier — the absolute pinnacle"   },
  A: { label: "Class A", description: "High performance — track-ready machines" },
  B: { label: "Class B", description: "Sport — iconic and thrilling"            },
};
export const getCarById   = (id)  => cars.find((c) => c.id === id);
export const getCarsByEra = (era) => cars.filter((c) => c.era === era);
export const featuredCar  = cars[5];